name: TomHaubner
favicon: null
layout_spectrum: 0.2580854813568294
typography_spectrum: 0.8586817723698914
title: Meine persönliche Seite
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6054280651733279
  lightness: 0.13340922677889466
  saturation: 0.9257516064681113
  rhythmicContrast: 0.28032989450730383
purpose: []
