name: TomHaubner
favicon: null
layout_spectrum: 0.24435
typography_spectrum: 0.14426
title: Meine persönliche Seite
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffd9'
    - '#230b09'
    - '#ffc385'
    - '#7a4535'
    - '#de8255'
  brandStrength: 0.625
  lightness: 0.13340922677889466
  saturation: 0.875
  rhythmicContrast: 0.28032989450730383
purpose: []
